name:  CI

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - actions/checkout@v1
    - name: Run a one-line script
      run: echo hello world!
    - name: Run a multi-line script
      run : 
        echo add other actions to the build job
        echo this can be unit tests, etc.